[theme]
base = "light"
primaryColor = "#db2777"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f5f9"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "viewer"
